version: '3.8'
services:
  okami-web:
    build: .
    labels:
      - "traefik.http.routers.okamiweb.rule=Host(`okami.phmarques.com.br`)"
      - "traefik.http.routers.okamiweb.entrypoints=web,websecure"
      - "traefik.http.routers.okamiweb.tls.certresolver=myresolver"
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true